language: go
go:
 - 1.8

addons:
  apt:
    packages:
     - python-pygments

install: go get -u -v github.com/gohugoio/hugo
script: hugo

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
  provider: pages
  skip_cleanup: true
