addons:
  apt:
    packages:
     - python-pygments

# TODO Update after https://github.com/travis-ci/gimme/issues/93 is resolved.
install:
 - eval "$(gimme 1.8.3)"
 - go get -u -v github.com/gohugoio/hugo
script: hugo -v

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
  provider: pages
  skip_cleanup: true
